version: '3.9'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
       MONGO_INITDB_DATABASE: myapp
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --quiet --logpath /dev/null

  user_service:
    build: ./user_service
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:example@mongo:27017/myapp
    depends_on:
      - mongo

  admission_service:
    build: ./ui_service
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api


  converter_service:
    build: ./converter_service
    ports:
      - '9090:9090'

  compiler_service:
    build: ./compiler_service
    ports:
      - '9292:9292'